# Arrays and Linear Algebra

## Arrays and Vectors

In [15]:
x = [1 2 3 4 5]  # produces a row vector

1x5 Array{Int64,2}:
 1  2  3  4  5

In [16]:
x'  # transpose x to a column vector

5x1 Array{Int64,2}:
 1
 2
 3
 4
 5

In [17]:
w = randperm(5)'   # row vector of random permutation of numbers 1 to 5

1x5 Array{Int64,2}:
 3  2  1  5  4

### Array Comprehensions

Julia has a neat syntax for constructing arrays from iterables that is very similar to mathematical notation.
For example, the squares of the numbers from 1 to 10 is

$$\{x^2: x \in \{1,\ldots,10\} \},$$

i.e. "the set of $x^2$ for $x$ from $1$ to $10$.  

In Julia we can write similar code to Python list comprehensions:

In [4]:
squares = [x^2 for x in 1:10]

10-element Array{Int64,1}:
   1
   4
   9
  16
  25
  36
  49
  64
  81
 100

###  Some Linear Algebra with Vectors

In [18]:
println("Add: ", x+w)
println("Subtract: ", x-w)
println("Inner product: ", w*x')   # inner product
println("Outer product:\n", x'*w)


Add: [4 4 4 9 9]
Subtract: [-2 0 2 -1 1]
Inner product: [50]
Outer product:
[3 2 1 5 4
 6 4 2 10 8
 9 6 3 15 12
 12 8 4 20 16
 15 10 5 25 20]


## Matrices, Multidimensional Arrays

In [20]:
M = [1 2 3 4; 5 6 7 8]   # semicolon denotes new row

2x4 Array{Int64,2}:
 1  2  3  4
 5  6  7  8

In [1]:
X = Array{Int8}(4,2)

4x2 Array{Int8,2}:
   56  -106
 -107   127
   32     0
  -85     0

In [22]:
X'  # transpose

2x4 Array{Int8,2}:
  32  -87  -69  -81
 105  127    0    0

In [23]:
W = Array{Int8}(2,3)

2x3 Array{Int8,2}:
 112  -14  105
  13  -80  127

### Some Liner Algebra with Matrices

In [25]:
X*W  # multiply matrices

4x3 Array{Int8,2}:
   85  112   55
   99   18   82
  -48  -58  -77
 -112  110  -57

However the following gives an error because the **inner dimensions** do not match:

In [26]:
W*X

LoadError: LoadError: DimensionMismatch("matrix A has dimensions (2,3), matrix B has dimensions (4,2)")
while loading In[26], in expression starting on line 1

Division, not so simple.

In [27]:
W'/X

3x4 Array{Float64,2}:
  0.45287   -0.272058  -0.45      -0.528261
 -0.436909  -0.268697   0.14258    0.167377
  0.981672   0.188382  -0.548342  -0.643705

## To Vectorise or Not?
In Octave and Matlab vectorising is good, in Julia it may not be. How you write the code may have a dramatic effect on its execution time.

Here are two functions that do the same thing but are implemented differently:

In [1]:
function vecadd1(a,b,c,N)
    for i = 1:N
      c = a + b 
    end
end

function vecadd2(a,b,c,N)
    for i = 1:N, j = 1:length(c)
      c[j] = a[j] + b[j]
    end
end

A = rand(2); B = rand(2); C = zeros(2)

N = 10000000;

In [2]:
@elapsed vecadd1(A,B,C,N)

1.124879583

In [3]:
@elapsed vecadd2(A,B,C,N)

0.103465399